package de.retest.recheck.example;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import de.retest.web.selenium.RecheckDriver;

public class CartTest {
	private RecheckDriver driver;

	@BeforeEach
	public void setUp() {
		final ChromeOptions opts = new ChromeOptions().addArguments( //
				"--headless", "--window-size=1200,800" );
		driver = new RecheckDriver( new ChromeDriver( opts ) );
	}

	@AfterEach
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void cart() {
		driver.get( "http://demowebshop.tricentis.com/" );
		driver.findElement( By.cssSelector( ".item-box:nth-child(3) img" ) ).click();
		driver.findElement( By.id( "add-to-cart-button-31" ) ).click();
		driver.findElement( By.cssSelector( ".cart-qty" ) ).click();
		driver.findElement( By.cssSelector( ".cart-item-row" ) ).click();
		driver.findElement(
				By.xpath( "/html/body/div[4]/div[1]/div[4]/div/div/div[2]/div/form/table/tbody/tr/td[5]/input" ) )
				.clear();
		driver.findElement(
				By.xpath( "/html/body/div[4]/div[1]/div[4]/div/div/div[2]/div/form/table/tbody/tr/td[5]/input" ) )
				.sendKeys( "0" );
		driver.findElement( By.name( "updatecart" ) ).click();
	}
}
